### ISSUE TITLE
Login - Estrutura de autenticação

### ISSUE THREAD

**Issue by dsalexan** [CodelabUnifesp/ibeac-web#49]
Implementar a estrutura de autenticação do site. Existem algumas bibliotecas por ai que facilitam isso no react, mas também da pra fazer só com cookie e JWT (esse projeto não pede nada muito rebuscado também).

---

https://www.youtube.com/watch?v=La_feUAG6UA&t=1s

**Comment by JoicyAlbuquerque** [comment]
Vou fazer essa
